### PR TITLE
non-semver version numbers

### LINKED ISSUE #35: [Bug] failing to parse "+" in dependency
To reproduce:

```
git clone https://github.com/magic-wormhole/magic-wormhole.rs
cd magic-wormhole.rs && cargo debstatus
```
log:
```
RUST_BACKTRACE=full cargo debstatus 
[46/201] Resolving debian packages ████████░░░░░░░░░░░░░░░░░░░░░░░░░░░thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: unexpected character '+' after major version number', src/debian.rs:66:54
stack backtrace:
   0:     0x5c0f8231fc9a - <unknown>
   1:     0x5c0f8235c55f - <unknown>
   2:     0x5c0f8232a655 - <unknown>
   3:     0x5c0f8231fa55 - <unknown>
   4:     0x5c0f82327a6e - <unknown>
   5:     0x5c0f82327729 - <unknown>
   6:     0x5c0f82327fc1 - <unknown>
   7:     0x5c0f8231ffc9 - <unknown>
   8:     0x5c0f8231fda6 - <unknown>
   9:     0x5c0f82327cc2 - <unknown>
  10:     0x5c0f820fa873 - <unknown>
  11:     0x5c0f820fa7a3 - <unknown>
  12:     0x5c0f82134b1f - <unknown>
  13:     0x5c0f82156c1f - <unknown>
  14:     0x5c0f82347b15 - <unknown>
  15:     0x7b2938a033ec - <unknown>
  16:     0x7b2938a83a4c - <unknown>
  17:                0x0 - <unknown>
```

I suspect this is cargo debstatus not accounting for Jonas' +ds/+dfsg 'd packages.

### PR DESCRIPTION
**Pull request by alexanderkjall**
It seems like Jonas Smedegaard have started to upload source package without semver compatible version numbers. If we encounter such a version number, try to pad it with '.0' so that it becomes compatible.

One example is: https://ftp-master.debian.org/new/rust-curve25519-dalek_4+20231122+dfsg-2.html

That has version number: 4+20231122+dfsg-2

Fixes #35

### CODE REVIEW

File: src/db.rs [hunk 1]
```diff
@@ -30,7 +30,22 @@ pub struct CacheEntry {
...
+            }
+            1 => {
+                format!("{}.0", parts[0])
+            }
+            2 => parts[0].to_owned(),
+            _ => {
+                return Err(anyhow!("wrong number of '.' characters in semver string"));
+            }
+        };
+    }
```
Comment (kpcyrd) [inline src/db.rs:48]: It's possible to avoid `parts[0]` entirely by matching on the return value of `.split_once`:

```suggestion
    if let Some((version, _suffix)) = debversion.split_once('+') {
        debversion = match version.matches('.').count() {
            0 => format!("{version}.0.0"),
            1 => format!("{version}.0"),
            2 => version.to_owned(),
            _ => bail!("wrong number of '.' characters in semver string: {version:?}")),
        };
    }
```

Also adding the version string into the error message to make it easier to debug. :)

Comment (alexanderkjall) [reply src/db.rs]: great suggestions, thanks :)

**Review by kpcyrd — APPROVED** [review]
